In [1]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [3]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\icecr\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\icecr\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.4-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\icecr\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp313-cp313-win_amd64.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.6 MB 8.9 MB/s eta 0:00:01
   -------------- ------------------------- 3.4/9.6 MB 11.2 MB/s eta 0:00:01
   ----------------------- ---------------- 5.8/9.6 MB 11.5 MB/s eta 0:00:01
   ---------------------------------- ----- 8.4/9.6 MB 11.6 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.6 MB 11.6 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 9.5 MB/s  0:00:01
Downloading tzdata-2026.4-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.6 tzdata-2026.4
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
print(pd.__version__)

3.0.6

In [5]:
months = ["Січ", "Лют", "Бер", "Кві", "Тра", "Чер",
          "Лип", "Сер", "Вер", "Жов", "Лис", "Гру"]

avg_temp = [-4, -3, 1, 7, 12, 15, 17, 16, 12, 7, 2, -2]

precip = [44, 42, 46, 58, 90, 105, 100, 82, 62, 52, 56, 50]

In [6]:
df = pd.DataFrame({
    "month": months,
    "avg_temp": avg_temp,
    "precip": precip,
})

df.head()

  month  avg_temp  precip
0   Січ        -4      44
1   Лют        -3      42
2   Бер         1      46
3   Кві         7      58
4   Тра        12      90

In [7]:
df.shape

(12, 3)

In [8]:
df.dtypes

month         str
avg_temp    int64
precip      int64
dtype: object

In [9]:
df

   month  avg_temp  precip
0    Січ        -4      44
1    Лют        -3      42
2    Бер         1      46
3    Кві         7      58
4    Тра        12      90
5    Чер        15     105
6    Лип        17     100
7    Сер        16      82
8    Вер        12      62
9    Жов         7      52
10   Лис         2      56
11   Гру        -2      50

In [10]:
df.index

RangeIndex(start=0, stop=12, step=1)

In [11]:
df = df.set_index("month")
df

       avg_temp  precip
month
Січ          -4      44
Лют          -3      42
Бер           1      46
Кві           7      58
Тра          12      90
Чер          15     105
Лип          17     100
Сер          16      82
Вер          12      62
Жов           7      52
Лис           2      56
Гру          -2      50

In [12]:
df.loc["Січ"]

avg_temp    -4
precip      44
Name: Січ, dtype: int64

In [13]:
df = df.reset_index()
df

   month  avg_temp  precip
0    Січ        -4      44
1    Лют        -3      42
2    Бер         1      46
3    Кві         7      58
4    Тра        12      90
5    Чер        15     105
6    Лип        17     100
7    Сер        16      82
8    Вер        12      62
9    Жов         7      52
10   Лис         2      56
11   Гру        -2      50

In [14]:
df.index = range(1, 13)
df

   month  avg_temp  precip
1    Січ        -4      44
2    Лют        -3      42
3    Бер         1      46
4    Кві         7      58
5    Тра        12      90
6    Чер        15     105
7    Лип        17     100
8    Сер        16      82
9    Вер        12      62
10   Жов         7      52
11   Лис         2      56
12   Гру        -2      50

In [15]:
df.loc[1:6, "avg_temp"]

1    -4
2    -3
3     1
4     7
5    12
6    15
Name: avg_temp, dtype: int64

In [16]:
df.iloc[0:6, 1]

1    -4
2    -3
3     1
4     7
5    12
6    15
Name: avg_temp, dtype: int64

In [17]:
df[["month", "precip"]]

   month  precip
1    Січ      44
2    Лют      42
3    Бер      46
4    Кві      58
5    Тра      90
6    Чер     105
7    Лип     100
8    Сер      82
9    Вер      62
10   Жов      52
11   Лис      56
12   Гру      50

In [18]:
df[df["avg_temp"] > 15]

  month  avg_temp  precip
7   Лип        17     100
8   Сер        16      82

In [19]:
df[(df["avg_temp"] > 10) & (df["precip"] > 50)]

  month  avg_temp  precip
5   Тра        12      90
6   Чер        15     105
7   Лип        17     100
8   Сер        16      82
9   Вер        12      62

In [20]:
df[(df["avg_temp"] < 0) | (df["precip"] > 80)]

   month  avg_temp  precip
1    Січ        -4      44
2    Лют        -3      42
5    Тра        12      90
6    Чер        15     105
7    Лип        17     100
8    Сер        16      82
12   Гру        -2      50

In [21]:
df["avg_temp_f"] = df["avg_temp"] * 9/5 + 32

In [22]:
df

   month  avg_temp  precip  avg_temp_f
1    Січ        -4      44        24.8
2    Лют        -3      42        26.6
3    Бер         1      46        33.8
4    Кві         7      58        44.6
5    Тра        12      90        53.6
6    Чер        15     105        59.0
7    Лип        17     100        62.6
8    Сер        16      82        60.8
9    Вер        12      62        53.6
10   Жов         7      52        44.6
11   Лис         2      56        35.6
12   Гру        -2      50        28.4

In [23]:
df["is_wet"] = df["precip"] > df["precip"].mean()

In [24]:
df

   month  avg_temp  precip  avg_temp_f  is_wet
1    Січ        -4      44        24.8   False
2    Лют        -3      42        26.6   False
3    Бер         1      46        33.8   False
4    Кві         7      58        44.6   False
5    Тра        12      90        53.6    True
6    Чер        15     105        59.0    True
7    Лип        17     100        62.6    True
8    Сер        16      82        60.8    True
9    Вер        12      62        53.6   False
10   Жов         7      52        44.6   False
11   Лис         2      56        35.6   False
12   Гру        -2      50        28.4   False

In [25]:
def get_season(month_num):
    if month_num in [12, 1, 2]:
        return "зима"
    elif month_num in [3, 4, 5]:
        return "весна"
    elif month_num in [6, 7, 8]:
        return "літо"
    else:
        return "осінь"

In [26]:
df["season"] = df.index.to_series().apply(get_season)

In [27]:
df

   month  avg_temp  precip  avg_temp_f  is_wet season
1    Січ        -4      44        24.8   False   зима
2    Лют        -3      42        26.6   False   зима
3    Бер         1      46        33.8   False  весна
4    Кві         7      58        44.6   False  весна
5    Тра        12      90        53.6    True  весна
6    Чер        15     105        59.0    True   літо
7    Лип        17     100        62.6    True   літо
8    Сер        16      82        60.8    True   літо
9    Вер        12      62        53.6   False  осінь
10   Жов         7      52        44.6   False  осінь
11   Лис         2      56        35.6   False  осінь
12   Гру        -2      50        28.4   False   зима

**1. Чому `df.loc[1:6]` і `df.iloc[0:6]` можуть повертати різну кількість рядків залежно від індексу?**

`loc` працює з мітками (значеннями) індексу, а `iloc` — з позиціями рядків. У `loc[1:6]` обидві межі включаються, тому будуть вибрані рядки з індексами 1, 2, 3, 4, 5 і 6. У `iloc[0:6]` права межа 6 не включається, тому вибираються позиції від 0 до 5. Якщо індекс має інші значення або не збігається з позиціями рядків, результати можуть відрізнятися.

**2. Чому `df["avg_temp"] > 10 and df["precip"] > 50` дає помилку, а `(df["avg_temp"] > 10) & (df["precip"] > 50)` працює?**

У `pandas` кожна умова повертає цілу серію значень `True` або `False`. Оператор `and` призначений для роботи з одиночними логічними значеннями і не може визначити одне значення істинності для всієї Series. Оператор `&` виконує поелементне логічне «І», тому він дозволяє перевірити дві умови для кожного рядка окремо. Кожну умову потрібно брати в дужки.

**3. Чим відрізняється створення обчислюваного стовпця через формулу від використання `.apply()`?**

При створенні стовпця через формулу операція виконується одразу над усім стовпцем або масивом значень. Наприклад, `df["avg_temp"] * 9/5 + 32` векторизовано перетворює всі значення температури. `.apply()` дозволяє застосувати власну функцію до окремих значень або рядків і використовувати складнішу логіку, наприклад визначення пори року за номером місяця.