In [3]:
import pandas as pd

months = ["Січ", "Лют", "Бер", "Кві", "Тра", "Чер",
          "Лип", "Сер", "Вер", "Жов", "Лис", "Гру"]

avg_temp = [-4, -3, 1, 7, 12, 15, 17, 16, 12, 7, 2, -2]

precip = [44, 42, 46, 58, 90, 105, 100, 82, 62, 52, 56, 50]

df = pd.DataFrame({
    "month": months,
    "avg_temp": avg_temp,
    "precip": precip,
})

df

   month  avg_temp  precip
0    Січ        -4      44
1    Лют        -3      42
2    Бер         1      46
3    Кві         7      58
4    Тра        12      90
5    Чер        15     105
6    Лип        17     100
7    Сер        16      82
8    Вер        12      62
9    Жов         7      52
10   Лис         2      56
11   Гру        -2      50

In [4]:
# Виведення індексу за замовчуванням
print("Індекс:")
print(df.index)

# Замінюємо індекс на month
df_by_month = df.set_index("month")

print("\nDataFrame з індексом month:")
display(df_by_month)

# Вибираємо рядок для місяця Лип
print("\nДані за Лип:")
display(df_by_month.loc["Лип"])

# Повертаємо звичайну нумерацію рядків
df = df_by_month.reset_index()

print("\nDataFrame після повернення звичайного індексу:")
display(df)

Індекс:
RangeIndex(start=0, stop=12, step=1)

DataFrame з індексом month:

       avg_temp  precip
month
Січ          -4      44
Лют          -3      42
Бер           1      46
Кві           7      58
Тра          12      90
Чер          15     105
Лип          17     100
Сер          16      82
Вер          12      62
Жов           7      52
Лис           2      56
Гру          -2      50

Дані за Лип:

avg_temp     17
precip      100
Name: Лип, dtype: int64

DataFrame після повернення звичайного індексу:

   month  avg_temp  precip
0    Січ        -4      44
1    Лют        -3      42
2    Бер         1      46
3    Кві         7      58
4    Тра        12      90
5    Чер        15     105
6    Лип        17     100
7    Сер        16      82
8    Вер        12      62
9    Жов         7      52
10   Лис         2      56
11   Гру        -2      50

In [5]:
# Встановлюємо числовий індекс від 1 до 12
df.index = range(1, 13)

print("DataFrame з індексом від 1 до 12:")
display(df)

# 1. Вибір avg_temp через .loc для індексів 1–6
print("avg_temp для місяців 1–6 через .loc:")
display(df.loc[1:6, "avg_temp"])

# 2. Вибір avg_temp через .iloc за позиціями 0–5
print("avg_temp за позиціями 0–5 через .iloc:")
display(df.iloc[0:6, 1])

# 3. Вибираємо тільки month і precip
print("Стовпці month і precip:")
display(df[["month", "precip"]])

DataFrame з індексом від 1 до 12:

   month  avg_temp  precip
1    Січ        -4      44
2    Лют        -3      42
3    Бер         1      46
4    Кві         7      58
5    Тра        12      90
6    Чер        15     105
7    Лип        17     100
8    Сер        16      82
9    Вер        12      62
10   Жов         7      52
11   Лис         2      56
12   Гру        -2      50

avg_temp для місяців 1–6 через .loc:

1    -4
2    -3
3     1
4     7
5    12
6    15
Name: avg_temp, dtype: int64

avg_temp за позиціями 0–5 через .iloc:

1    -4
2    -3
3     1
4     7
5    12
6    15
Name: avg_temp, dtype: int64

Стовпці month і precip:

   month  precip
1    Січ      44
2    Лют      42
3    Бер      46
4    Кві      58
5    Тра      90
6    Чер     105
7    Лип     100
8    Сер      82
9    Вер      62
10   Жов      52
11   Лис      56
12   Гру      50

In [6]:
# 1. Місяці, де avg_temp > 15
print("Місяці, де avg_temp > 15:")
display(df.loc[df["avg_temp"] > 15, "month"])

# 2. Місяці, де avg_temp > 10 і precip > 50
print("\nМісяці, де avg_temp > 10 і precip > 50:")
display(
    df.loc[
        (df["avg_temp"] > 10) & (df["precip"] > 50),
        "month"
    ]
)

# 3. Місяці, де avg_temp < 0 або precip > 80
print("\nМісяці, де avg_temp < 0 або precip > 80:")
display(
    df.loc[
        (df["avg_temp"] < 0) | (df["precip"] > 80),
        "month"
    ]
)

Місяці, де avg_temp > 15:

7    Лип
8    Сер
Name: month, dtype: str

Місяці, де avg_temp > 10 і precip > 50:

5    Тра
6    Чер
7    Лип
8    Сер
9    Вер
Name: month, dtype: str

Місяці, де avg_temp < 0 або precip > 80:

1     Січ
2     Лют
5     Тра
6     Чер
7     Лип
8     Сер
12    Гру
Name: month, dtype: str

In [7]:
# 1. Температура у Фаренгейтах
df["avg_temp_f"] = df["avg_temp"] * 9 / 5 + 32

# 2. True, якщо опади більші за середнє значення
mean_precip = df["precip"].mean()
df["is_wet"] = df["precip"] > mean_precip

# 3. Функція для визначення пори року
def get_season(month_number):
    if month_number in [12, 1, 2]:
        return "зима"
    elif month_number in [3, 4, 5]:
        return "весна"
    elif month_number in [6, 7, 8]:
        return "літо"
    else:
        return "осінь"

# Створюємо стовпець season через apply()
df["season"] = df.index.to_series().apply(get_season)

print("Середня кількість опадів:", mean_precip)
display(df)

Середня кількість опадів: 65.58333333333333

   month  avg_temp  precip  avg_temp_f  is_wet season
1    Січ        -4      44        24.8   False   зима
2    Лют        -3      42        26.6   False   зима
3    Бер         1      46        33.8   False  весна
4    Кві         7      58        44.6   False  весна
5    Тра        12      90        53.6    True  весна
6    Чер        15     105        59.0    True   літо
7    Лип        17     100        62.6    True   літо
8    Сер        16      82        60.8    True   літо
9    Вер        12      62        53.6   False  осінь
10   Жов         7      52        44.6   False  осінь
11   Лис         2      56        35.6   False  осінь
12   Гру        -2      50        28.4   False   зима

## Письмові відповіді

### 1. Чому `.loc[1:6]` і `.iloc[0:6]` можуть повернути різну кількість рядків?

`.loc` вибирає рядки за значеннями індексу, тобто за його підписами. `.iloc` вибирає рядки за їхніми позиціями в таблиці. Також `.loc[1:6]` включає індекс 6, а `.iloc[0:6]` не включає позицію 6. Тому кількість отриманих рядків може відрізнятися.

### 2. Чому `and` викликає помилку, а `&` працює?

У pandas порівняння стовпців створює Series з багатьма логічними значеннями. Оператор `and` призначений для одиничних логічних значень і не може працювати з усією Series. Оператор `&` виконує поелементне логічне І, тому його використовують для об'єднання умов у pandas.

### 3. У чому різниця між обчислюваним стовпцем через формулу і через `.apply()`?

Обчислюваний стовпець через формулу створюється векторизованою операцією одразу для всіх значень стовпця. Це простий і швидкий спосіб виконання обчислень. `.apply()` дозволяє застосувати власну функцію до окремих значень і використовується, коли потрібна складніша логіка, наприклад визначення пори року за номером місяця.