Практика 3. Приведення до tidy data

Варіант: 3  
Місто: Одеса

Питання 1
Чи можете пояснити, чому стовпець "місто" — номінальна шкала, а стовпець "хмарність" — шкала відношень?


Місто належить до номінальної шкали, оскільки це назви категорій, між якими немає природного порядку. Хмарність належить до шкали відношень, оскільки вимірюється у відсотках, має природний нуль — 0% хмарності, а співвідношення між значеннями має зміст.

Питання 2
Чи розумієте, чому вихідна wide-таблиця з місяцями в стовпцях не вважається tidy, і що саме змінюється в її структурі після melt()?


Вихідна wide-таблиця не є tidy, оскільки змінна «місяць» представлена не окремим стовпцем, а назвами 12 різних стовпців. Після застосування melt() усі місяці перетворюються на значення одного стовпця «місяць», а відповідні значення хмарності — на стовпець «хмарність». Тому одна спостережувана величина для кожного місяця займає окремий рядок.

Можна навіть додати:

Було:

місто | Січ | Лют | Бер | ... | Гру

Стало:

місто | місяць | хмарність
Одеса | Січ    | 70
Одеса | Лют    | 66


Питання 3
Чи можете описати, чим формат CSV принципово відрізняється від JSON при зберіганні однієї й тієї самої таблиці?

CSV представляє дані як рядки та стовпці, розділені спеціальним символом, наприклад комою, тому він добре підходить для табличних даних. JSON представляє дані у структурованому вигляді як об'єкти та масиви, де кожне поле має ключ і значення. Тому JSON є більш гнучким для представлення складних структур даних, а CSV є простішим для табличного зберігання.

In [17]:
print(open("variant.json", encoding="utf-8").read())

[{"місто":"Одеса","місяць":"Січ","хмарність":70},{"місто":"Одеса","місяць":"Лют","хмарність":66},{"місто":"Одеса","місяць":"Бер","хмарність":60},{"місто":"Одеса","місяць":"Кві","хмарність":50},{"місто":"Одеса","місяць":"Тра","хмарність":42},{"місто":"Одеса","місяць":"Чер","хмарність":36},{"місто":"Одеса","місяць":"Лип","хмарність":32},{"місто":"Одеса","місяць":"Сер","хмарність":34},{"місто":"Одеса","місяць":"Вер","хмарність":44},{"місто":"Одеса","місяць":"Жов","хмарність":58},{"місто":"Одеса","місяць":"Лис","хмарність":68},{"місто":"Одеса","місяць":"Гру","хмарність":74}]

In [16]:
print(open("variant.csv", encoding="utf-8").read())

місто,місяць,хмарність
Одеса,Січ,70
Одеса,Лют,66
Одеса,Бер,60
Одеса,Кві,50
Одеса,Тра,42
Одеса,Чер,36
Одеса,Лип,32
Одеса,Сер,34
Одеса,Вер,44
Одеса,Жов,58
Одеса,Лис,68
Одеса,Гру,74

In [15]:
print(tidy.equals(reloaded_json))

True

In [14]:
print(tidy.equals(reloaded_csv))

True

In [13]:
reloaded_json = pd.read_json("variant.json")

reloaded_json

    місто місяць  хмарність
0   Одеса    Січ         70
1   Одеса    Лют         66
2   Одеса    Бер         60
3   Одеса    Кві         50
4   Одеса    Тра         42
5   Одеса    Чер         36
6   Одеса    Лип         32
7   Одеса    Сер         34
8   Одеса    Вер         44
9   Одеса    Жов         58
10  Одеса    Лис         68
11  Одеса    Гру         74

In [12]:
reloaded_csv = pd.read_csv("variant.csv")

reloaded_csv

    місто місяць  хмарність
0   Одеса    Січ         70
1   Одеса    Лют         66
2   Одеса    Бер         60
3   Одеса    Кві         50
4   Одеса    Тра         42
5   Одеса    Чер         36
6   Одеса    Лип         32
7   Одеса    Сер         34
8   Одеса    Вер         44
9   Одеса    Жов         58
10  Одеса    Лис         68
11  Одеса    Гру         74

In [11]:
tidy.to_json(
    "variant.json",
    orient="records",
    force_ascii=False
)

In [10]:
tidy.to_csv("variant.csv", index=False)

In [9]:
original_values = wide.set_index("місто").sort_index(axis=1)
back_values = back.sort_index(axis=1)

print(original_values.equals(back_values))

True

In [8]:
print(back.shape)

(1, 12)

In [7]:
back = tidy.pivot(
    index="місто",
    columns="місяць",
    values="хмарність"
)

back

місяць  Бер  Вер  Гру  Жов  Кві  Лип  Лис  Лют  Сер  Січ  Тра  Чер
місто
Одеса    60   44   74   58   50   32   68   66   34   70   42   36

In [6]:
print(tidy.shape)

(12, 3)

In [5]:
tidy = wide.melt(
    id_vars="місто",
    var_name="місяць",
    value_name="хмарність"
)

In [4]:
tidy = wide.melt(
    id_vars="місто",
    var_name="місяць",
    value_name="хмарність"
)

tidy

    місто місяць  хмарність
0   Одеса    Січ         70
1   Одеса    Лют         66
2   Одеса    Бер         60
3   Одеса    Кві         50
4   Одеса    Тра         42
5   Одеса    Чер         36
6   Одеса    Лип         32
7   Одеса    Сер         34
8   Одеса    Вер         44
9   Одеса    Жов         58
10  Одеса    Лис         68
11  Одеса    Гру         74

In [3]:
print(wide.shape)

(1, 13)

In [2]:
wide = pd.DataFrame({
    "місто": ["Одеса"],
    "Січ": [70],
    "Лют": [66],
    "Бер": [60],
    "Кві": [50],
    "Тра": [42],
    "Чер": [36],
    "Лип": [32],
    "Сер": [34],
    "Вер": [44],
    "Жов": [58],
    "Лис": [68],
    "Гру": [74]
})

wide

   місто  Січ  Лют  Бер  Кві  Тра  Чер  Лип  Сер  Вер  Жов  Лис  Гру
0  Одеса   70   66   60   50   42   36   32   34   44   58   68   74

In [1]:
import pandas as pd