# Практична робота №3
## Дисципліна: Аналіз даних та математичне моделювання
### Тема: Приведення до tidy data

- **Студент:** Хрустовський Павло
- **Група:** ІТ-42
- **Варіант:** 2 (Місто: Львів)
- **Мета роботи:** Перетворити таблицю з wide-формату в tidy (long) і назад, класифікувати змінні за шкалою вимірювання та прочитати й записати таблицю в форматах CSV і JSON — на прикладі з лекції 3.

---
## Демонстраційний приклад: наскрізна демонстрація
Розбір наскрізного прикладу на демонстраційному наборі даних (квартальна виручка трьох умовних магазинів) перед виконанням завдань на власному варіанті.

In [1]:
import pandas as pd

# 1. Створення wide-таблиці для трьох магазинів
wide_demo = pd.DataFrame({
    "магазин": ["Центр", "Північний", "Південний"],
    "Q1": [120_000, 95_000, 88_000],
    "Q2": [135_000, 101_000, 92_000],
    "Q3": [128_000, 98_000, 95_000],
    "Q4": [160_000, 112_000, 110_000],
})
print("Wide-формат демонстраційного набору:")
display(wide_demo)

# 2. wide -> tidy (long): квартал стає значенням, а не назвою стовпця
tidy_demo = wide_demo.melt(id_vars="магазин", var_name="квартал", value_name="виручка")
print("\nTidy (long) формат:")
display(tidy_demo)

# 3. tidy -> wide: обернена операція, зручна для звіту
back_demo = tidy_demo.pivot(index="магазин", columns="квартал", values="виручка")
print("\nПовернення у wide-формат через pivot():")
display(back_demo)

# 4. Запис і читання у двох форматах
tidy_demo.to_csv("demo_tidy.csv", index=False)
tidy_demo.to_json("demo_tidy.json", orient="records", force_ascii=False)
reloaded_demo_csv = pd.read_csv("demo_tidy.csv")
reloaded_demo_json = pd.read_json("demo_tidy.json")

print(f"\nЗбіг CSV з оригіналом demo: {reloaded_demo_csv.equals(tidy_demo)}")
print(f"Збіг JSON з оригіналом demo: {reloaded_demo_json.equals(tidy_demo)}")

Wide-формат демонстраційного набору:

     магазин      Q1      Q2      Q3      Q4
0      Центр  120000  135000  128000  160000
1  Північний   95000  101000   98000  112000
2  Південний   88000   92000   95000  110000

Tidy (long) формат:

      магазин квартал  виручка
0       Центр      Q1   120000
1   Північний      Q1    95000
2   Південний      Q1    88000
3       Центр      Q2   135000
4   Північний      Q2   101000
5   Південний      Q2    92000
6       Центр      Q3   128000
7   Північний      Q3    98000
8   Південний      Q3    95000
9       Центр      Q4   160000
10  Північний      Q4   112000
11  Південний      Q4   110000

Повернення у wide-формат через pivot():

квартал        Q1      Q2      Q3      Q4
магазин
Південний   88000   92000   95000  110000
Північний   95000  101000   98000  112000
Центр      120000  135000  128000  160000

Збіг CSV з оригіналом demo: True
Збіг JSON з оригіналом demo: True

---
## Завдання 1. Побудова wide-таблиці свого варіанта

Згідно з **Варіантом 2** (місто **Львів**), значення середньої хмарності (%) по місяцях становлять:
- **Січ:** 82%, **Лют:** 78%, **Бер:** 72%, **Кві:** 62%, **Тра:** 55%, **Чер:** 48%
- **Лип:** 44%, **Сер:** 46%, **Вер:** 56%, **Жов:** 70%, **Лис:** 80%, **Гру:** 85%

Зберемо таблицю свого варіанта у DataFrame рівно в тому вигляді, як вона подана в умові (wide-формат з одним рядком).

In [2]:
# Побудова wide-таблиці для Варіанта 2 (Львів)
wide = pd.DataFrame({
    "місто": ["Львів"],
    "Січ": [82],
    "Лют": [78],
    "Бер": [72],
    "Кві": [62],
    "Тра": [55],
    "Чер": [48],
    "Лип": [44],
    "Сер": [46],
    "Вер": [56],
    "Жов": [70],
    "Лис": [80],
    "Гру": [85],
})

print(f"Форма таблиці (shape): {wide.shape}")
display(wide)

Форма таблиці (shape): (1, 13)

   місто  Січ  Лют  Бер  Кві  Тра  Чер  Лип  Сер  Вер  Жов  Лис  Гру
0  Львів   82   78   72   62   55   48   44   46   56   70   80   85

---
## Завдання 2. Приведення до tidy (melt)

Перетворимо таблицю на tidy-формат за допомогою функції `melt()` так, щоб отримати стовпці:
- `"місто"`
- `"місяць"`
- `"хмарність"`

Також перевіримо розмірність результату (`shape`) і пояснимо структуру отриманих даних.

In [3]:
# Приведення до tidy-формату
tidy = wide.melt(id_vars="місто", var_name="місяць", value_name="хмарність")

print(f"Форма результуючої tidy-таблиці (shape): {tidy.shape}")
display(tidy)

Форма результуючої tidy-таблиці (shape): (12, 3)

    місто місяць  хмарність
0   Львів    Січ         82
1   Львів    Лют         78
2   Львів    Бер         72
3   Львів    Кві         62
4   Львів    Тра         55
5   Львів    Чер         48
6   Львів    Лип         44
7   Львів    Сер         46
8   Львів    Вер         56
9   Львів    Жов         70
10  Львів    Лис         80
11  Львів    Гру         85

### Пояснення форми результату (shape):
Результат має форму **(12, 3)** — тобто **12 рядків** та **3 стовпці**:
- **Чому у вихідній wide-таблиці був 1 рядок:** у ній об'єкт спостереження («Львів») був записаний в одному рядку, а всі 12 вимірювань хмарності для різних місяців були розподілені по 12 окремих стовпцях («Січ», «Лют», ..., «Гру»).
- **Чому в tidy-таблиці стало 12 рядків:** операція `melt()` виконала депівотування (unpivoting). Кожен з 12 місячних стовпців розгорнувся в окреме атомарне спостереження (окремий рядок). Назва місяця стала значенням у стовпці `"місяць"`, а величина хмарності — у стовпці `"хмарність"`. Відповідно, $1 \text{ місто} \times 12 \text{ місяців} = 12 \text{ рядків}$.

---
## Завдання 3. Класифікація змінних за шкалами вимірювання

Для кожного зі стовпців tidy-таблиці (`місто`, `місяць`, `хмарність`) визначимо шкалу вимірювання (номінальна / порядкова / інтервальна / відносна) та обґрунтуємо вибір:

1. **`місто` — Номінальна шкала (шкала найменувань / nominal):**
   Значення є якісними назвами категорій (назвами населених пунктів), для яких не існує природного порядку або числових відстаней, а допустимою математичною операцією є лише перевірка на рівність чи відмінність ($A = B$ або $A \neq B$).

2. **`місяць` — Порядкова шкала (ординальна / ordinal):**
   Місяці мають фіксовану природну хронологічну послідовність чергування в календарі (Січ < Лют < Бер < ... < Гру), що дозволяє їх ранжувати та впорядковувати, проте безпосередня різниця між ними не вимірюється метричною відстанню без додаткової прив'язки до кількості днів або точних дат.

3. **`хмарність` — Шкала відношень (відносна шкала / ratio):**
   Хмарність вимірюється у відсотках покриття небосхилу (0–100%) і має природний абсолютний нуль (0% означає повну відсутність хмарності / безхмарне небо), завдяки чому коректними є не лише операції різниці (на скільки більше/менше), але й обчислення пропорцій та відношень (у скільки разів одна хмарність більша за іншу).

| Стовпець | Тип даних | Шкала вимірювання | Допустимі операції | Обґрунтування вибору |
|:---|:---|:---|:---|:---|
| **`місто`** | Рядковий (object) | **Номінальна** | $=, \neq$ | Якісна назва населеного пункту без природного ранжування чи математичних дій. |
| **`місяць`** | Рядковий (object) | **Порядкова** | $=, \neq, <, >$ | Категорія з природним часовим порядком проходження місяців у календарному році. |
| **`хмарність`** | Числовий (int64) | **Відносна (шкала відношень)** | $=, \neq, <, >, +, -, \times, \div$ | Кількісний показник у відсотках із природним абсолютним нулем (0% — відсутність хмар). |

---
## Завдання 4. Зворотне перетворення й перевірка (pivot)

Виконаємо операцію `pivot()` над tidy-таблицею, щоб повернутися до wide-формату.
Після цього відновимо вихідний порядок стовпців місяців та перевіримо тотожність отриманої таблиці з таблицею із Завдання 1.

In [4]:
# Зворотне перетворення tidy -> wide за допомогою pivot()
back = tidy.pivot(index="місто", columns="місяць", values="хмарність")

# Відновлюємо початковий хронологічний порядок стовпців та скидаємо індекс
months_order = ["Січ", "Лют", "Бер", "Кві", "Тра", "Чер", "Лип", "Сер", "Вер", "Жов", "Лис", "Гру"]
back = back.reindex(columns=months_order).reset_index()
back.columns.name = None

print("Отримана таблиця після pivot() та впорядкування стовпців:")
display(back)

print("\nОригінальна wide-таблиця із Завдання 1:")
display(wide)

# Порівняння за допомогою методу equals()
is_identical = back.equals(wide)
print(f"\nЧи збігаються таблиці за структурою та значеннями (equals): {is_identical}")

Отримана таблиця після pivot() та впорядкування стовпців:

   місто  Січ  Лют  Бер  Кві  Тра  Чер  Лип  Сер  Вер  Жов  Лис  Гру
0  Львів   82   78   72   62   55   48   44   46   56   70   80   85

Оригінальна wide-таблиця із Завдання 1:

   місто  Січ  Лют  Бер  Кві  Тра  Чер  Лип  Сер  Вер  Жов  Лис  Гру
0  Львів   82   78   72   62   55   48   44   46   56   70   80   85

Чи збігаються таблиці за структурою та значеннями (equals): True

---
## Завдання 5. Читання й запис (CSV та JSON)

1. Запишемо отриману tidy-таблицю у файл `variant.csv` (без індексу) та у файл `variant.json` (`orient="records"`).
2. Прочитаємо обидва файли назад у нові DataFrame і переконаємося, що дані повністю збігаються з оригіналом.
3. Виведемо текстовий вміст обох файлів та опишемо відмінності в їхній структурі.

In [5]:
# 1. Запис tidy-таблиці у файли CSV та JSON
csv_filename = "variant.csv"
json_filename = "variant.json"

tidy.to_csv(csv_filename, index=False)
tidy.to_json(json_filename, orient="records", force_ascii=False, indent=2)

print(f"Дані успішно збережено у файли: {csv_filename}, {json_filename}")

Дані успішно збережено у файли: variant.csv, variant.json

In [6]:
# 2. Зчитування файлів назад у нові DataFrame та перевірка збігу
reloaded_csv = pd.read_csv(csv_filename)
reloaded_json = pd.read_json(json_filename)

print("Таблиця, зчитана з variant.csv:")
display(reloaded_csv.head(4))

print("\nТаблиця, зчитана з variant.json:")
display(reloaded_json.head(4))

# Перевірка збігу
print(f"\nДані з CSV збігаються з оригінальною tidy-таблицею: {reloaded_csv.equals(tidy)}")
print(f"Дані з JSON збігаються з оригінальною tidy-таблицею: {reloaded_json.equals(tidy)}")

Таблиця, зчитана з variant.csv:

   місто місяць  хмарність
0  Львів    Січ         82
1  Львів    Лют         78
2  Львів    Бер         72
3  Львів    Кві         62

Таблиця, зчитана з variant.json:

   місто місяць  хмарність
0  Львів    Січ         82
1  Львів    Лют         78
2  Львів    Бер         72
3  Львів    Кві         62

Дані з CSV збігаються з оригінальною tidy-таблицею: True
Дані з JSON збігаються з оригінальною tidy-таблицею: True

In [7]:
# 3. Виведення текстового вмісту файлів для порівняння структури
print(f"=== Вміст файлу {csv_filename} ===")
with open(csv_filename, "r", encoding="utf-8") as f:
    print(f.read())

print(f"=== Вміст файлу {json_filename} ===")
with open(json_filename, "r", encoding="utf-8") as f:
    print(f.read())

=== Вміст файлу variant.csv ===
місто,місяць,хмарність
Львів,Січ,82
Львів,Лют,78
Львів,Бер,72
Львів,Кві,62
Львів,Тра,55
Львів,Чер,48
Львів,Лип,44
Львів,Сер,46
Львів,Вер,56
Львів,Жов,70
Львів,Лис,80
Львів,Гру,85

=== Вміст файлу variant.json ===
[
  {
    "місто":"Львів",
    "місяць":"Січ",
    "хмарність":82
  },
  {
    "місто":"Львів",
    "місяць":"Лют",
    "хмарність":78
  },
  {
    "місто":"Львів",
    "місяць":"Бер",
    "хмарність":72
  },
  {
    "місто":"Львів",
    "місяць":"Кві",
    "хмарність":62
  },
  {
    "місто":"Львів",
    "місяць":"Тра",
    "хмарність":55
  },
  {
    "місто":"Львів",
    "місяць":"Чер",
    "хмарність":48
  },
  {
    "місто":"Львів",
    "місяць":"Лип",
    "хмарність":44
  },
  {
    "місто":"Львів",
    "місяць":"Сер",
    "хмарність":46
  },
  {
    "місто":"Львів",
    "місяць":"Вер",
    "хмарність":56
  },
  {
    "місто":"Львів",
    "місяць":"Жов",
    "хмарність":70
  },
  {
    "місто":"Львів",
    "місяць":"Лис",
    "хмарність":80
  },
  {
    "місто":"Львів",
    "місяць":"Гру",
    "хмарність":85
  }
]

### Порівняльний опис структури файлів CSV та JSON:
1. **Структура CSV (`variant.csv`):**
   - **Таблично-орієнтована плоска структура.**
   - У першому рядку записуються назви стовпців через кому (`місто,місяць,хмарність`).
   - Кожен наступний рядок відповідає одному запису даних, де значення стовпців розташовані в тій самій фіксованій послідовності.
   - Заголовки зберігаються лише один раз, завдяки чому формат є компактним за розміром, але не містить інформації про типи даних і не підтримує ієрархічні вкладення.

2. **Структура JSON (`variant.json` при `orient="records"`):**
   - **Об'єктно-орієнтована структура пар «ключ — значення».**
   - Дані зберігаються як масив окремих словників (об'єктів): `[{"місто": "Львів", "місяць": "Січ", "хмарність": 82}, ...]`.
   - Кожен запис є самодокументованим: назви атрибутів (ключі) дублюються для кожного рядка, що збільшує обсяг файлу, проте дає змогу легко обробляти дані у веб-застосунках, не залежати від порядку полів та зберігати вкладені структури.

---
## Відповіді на контрольні запитання

### 1. Чи можете пояснити, чому стовпець "місто" — номінальна шкала, а стовпець "хмарність" — шкала відношень?
- **Стовпець «місто» (номінальна шкала):**
  Значення цього стовпця («Львів», «Київ» тощо) є якісними назвами (мітками категорій). Між ними немає природного фізичного чи математичного порядку ранжування; неможливо сказати, що «Львів» більший чи менший за інше місто з точки зору цієї змінної. Для значень у номінальній шкалі єдиною визначеною математичною операцією є перевірка на еквівалентність (чи належать два об'єкти до одного класу/міста: $A = B$ або $A \neq B$).
- **Стовпець «хмарність» (шкала відношень):**
  Хмарність є кількісною неперервною величиною, вираженою у відсотках (0–100%), і має **природний абсолютний нуль** (0% — це повна відсутність хмарності, ясне небо). Завдяки наявності абсолютного нуля коректними є не лише операції віднімання (на скільки відсотків хмарність одного місяця перевищує хмарність іншого), але й операції ділення та множення (у скільки разів одна хмарність більша за іншу: наприклад, 80% хмарності в листопаді є рівно вдвічі більшою за 40% хмарності в липні).

---

### 2. Чи розумієте, чому вихідна wide-таблиця з місяцями в стовпцях не вважається tidy, і що саме змінюється в її структурі після `melt()`?
- **Чому wide-таблиця не є tidy:**
  Згідно з фундаментальними правилами Tidy Data (Hadley Wickham):
  1. Кожна змінна повинна знаходитися у своєму окремому стовпці.
  2. Кожне окреме спостереження повинно знаходитися в окремому рядку.
  3. Кожне значення повинно знаходитися у своїй окремій комірці.
  У вихідній таблиці назви 12 календарних місяців («Січ», «Лют», ..., «Гру») були заголовками стовпців. Проте «місяць» — це не окремі незалежні змінні, а **різні значення однієї й тієї самої змінної часу**. Водночас значення хмарності були розпорошені по 12 стовпцях, а 12 різних спостережень були спресовані в один спільний рядок.
- **Що змінюється після `melt()`:**
  - Назви стовпців («Січ», ..., «Гру») перетворюються на категоріальні значення нового єдиного стовпця `"місяць"`.
  - Числові показники збираються в єдиний числовий стовпець `"хмарність"`.
  - Кількість рядків збільшується до 12, перетворюючи кожен рядок на єдине повноцінне спостереження пари (місто, місяць) з відповідним значенням хмарності.

---

### 3. Чи можете описати, чим формат CSV принципово відрізняється від JSON при зберіганні однієї й тієї самої таблиці?
1. **Модель зберігання даних:**
   - **CSV** є плоским двовимірним форматом із матричною структурою. Схема (імена колонок) оголошується лише один раз у першому рядку, а значення записуються послідовно через розділювач.
   - **JSON** є форматом ієрархічних даних на базі списків та словників (пар «ключ — значення»). При збереженні `orient="records"` кожен рядок стає окремим автономним словником.
2. **Надмірність і компактність:**
   - **CSV** набагато компактніший, оскільки назви полів не повторюються для кожного рядка.
   - **JSON** містить надлишковість через постійне дублювання ключів (`"місто"`, `"місяць"`, `"хмарність"` у кожному об'єкті), проте це забезпечує повну самоописність кожного окремого запису незалежно від контексту файлу.
3. **Типізація та гнучкість:**
   - **CSV** не зберігає інформацію про типи даних (все зберігається як текст) і не підтримує вкладеності.
   - **JSON** на рівні специфікації розрізняє числа, рядки, булеві типи, масиви та значення `null`, а також дозволяє зберігати складні вкладені об'єкти будь-якого рівня глибини.

---
## Висновки
У ході виконання практичної роботи №3 було успішно виконано всі поставлені завдання:
1. Побудовано wide-таблицю навчального набору даних для **Варіанта 2 (місто Львів)**.
2. За допомогою функції `pandas.melt()` реалізовано депівотування таблиці у tidy-формат (12 рядків × 3 стовпці).
3. Здійснено класифікацію змінних за шкалами вимірювання Стівенса (`місто` — номінальна, `місяць` — порядкова, `хмарність` — відносна).
4. Проведено зворотне перетворення у wide-формат за допомогою `pandas.pivot()` та за допомогою `equals()` верифіковано тотожність отриманого результату початковим даним.
5. Збережено tidy-таблицю у форматах CSV (`variant.csv`) та JSON (`variant.json`), перевірено коректність їх зворотного зчитування та надано детальний порівняльний аналіз їхньої структури.
6. Надано вичерпні письмові відповіді на всі контрольні запитання.