In [1]:
import pandas as pd

In [2]:
wide = pd.DataFrame({
    "місто": ["Івано-Франківськ"],
    "Січ": [84],
    "Лют": [80],
    "Бер": [74],
    "Кві": [64],
    "Тра": [57],
    "Чер": [50],
    "Лип": [46],
    "Сер": [48],
    "Вер": [58],
    "Жов": [72],
    "Лис": [82],
    "Гру": [86],
})

wide

,місто,Січ,Лют,Бер,Кві,Тра,Чер,Лип,Сер,Вер,Жов,Лис,Гру
0,Івано-Франківськ,84,80,74,64,57,50,46,48,58,72,82,86

In [3]:
tidy = wide.melt(
    id_vars="місто",
    var_name="місяць",
    value_name="хмарність"
)

tidy

               місто місяць  хмарність
0   Івано-Франківськ    Січ         84
1   Івано-Франківськ    Лют         80
2   Івано-Франківськ    Бер         74
3   Івано-Франківськ    Кві         64
4   Івано-Франківськ    Тра         57
5   Івано-Франківськ    Чер         50
6   Івано-Франківськ    Лип         46
7   Івано-Франківськ    Сер         48
8   Івано-Франківськ    Вер         58
9   Івано-Франківськ    Жов         72
10  Івано-Франківськ    Лис         82
11  Івано-Франківськ    Гру         86

In [4]:
tidy.shape

(12, 3)

In [5]:
back = tidy.pivot(
    index="місто",
    columns="місяць",
    values="хмарність"
)

back

місяць            Бер  Вер  Гру  Жов  Кві  Лип  Лис  Лют  Сер  Січ  Тра  Чер
місто
Івано-Франківськ   74   58   86   72   64   46   82   80   48   84   57   50

In [6]:
back = back.reindex(columns=wide.columns[1:])
back

                  Січ  Лют  Бер  Кві  Тра  Чер  Лип  Сер  Вер  Жов  Лис  Гру
місто
Івано-Франківськ   84   80   74   64   57   50   46   48   58   72   82   86

In [7]:
back_reset = back.reset_index()
back_reset.equals(wide)

True

In [8]:
tidy.to_csv("variant.csv", index=False)
tidy.to_json("variant.json", orient="records", force_ascii=False)

In [9]:
reloaded_csv = pd.read_csv("variant.csv")
reloaded_json = pd.read_json("variant.json")

reloaded_csv

               місто місяць  хмарність
0   Івано-Франківськ    Січ         84
1   Івано-Франківськ    Лют         80
2   Івано-Франківськ    Бер         74
3   Івано-Франківськ    Кві         64
4   Івано-Франківськ    Тра         57
5   Івано-Франківськ    Чер         50
6   Івано-Франківськ    Лип         46
7   Івано-Франківськ    Сер         48
8   Івано-Франківськ    Вер         58
9   Івано-Франківськ    Жов         72
10  Івано-Франківськ    Лис         82
11  Івано-Франківськ    Гру         86

In [10]:
reloaded_csv.equals(tidy)

True

In [11]:
reloaded_json.equals(tidy)

True

In [12]:
print(open("variant.csv", encoding="utf-8").read())

місто,місяць,хмарність
Івано-Франківськ,Січ,84
Івано-Франківськ,Лют,80
Івано-Франківськ,Бер,74
Івано-Франківськ,Кві,64
Івано-Франківськ,Тра,57
Івано-Франківськ,Чер,50
Івано-Франківськ,Лип,46
Івано-Франківськ,Сер,48
Івано-Франківськ,Вер,58
Івано-Франківськ,Жов,72
Івано-Франківськ,Лис,82
Івано-Франківськ,Гру,86

**1. Чому «місто» — номінальна шкала, а «хмарність» — шкала відношень?**

«Місто» — номінальна шкала, тому що це назва категорії без числового значення та природного порядку. «Хмарність» — шкала відношень, оскільки має змістовний нуль: 0% означає відсутність хмарності, а співвідношення між значеннями можна інтерпретувати.

**2. Чому wide-таблиця не є tidy і що змінюється після `melt()`?**

У wide-таблиці місяці представлені окремими стовпцями, тому одна змінна «місяць» розподілена між назвами стовпців. Після `melt()` назви місяців перетворюються на значення одного стовпця «місяць», а значення хмарності — на стовпець «хмарність». У результаті кожен рядок описує одне спостереження.

**3. Чим CSV відрізняється від JSON?**

CSV зберігає дані у вигляді рядків і стовпців, розділених роздільником. JSON з `orient="records"` зберігає таблицю як масив об'єктів, де кожен об'єкт містить пари «назва поля: значення». JSON має більш структурований формат і може зберігати складніші вкладені дані, тоді як CSV простіший для табличних даних.