In [1]:
import pandas as pd

wide = pd.DataFrame({
    "місто": ["Суми"],
    "Січ": [79],
    "Лют": [75],
    "Бер": [69],
    "Кві": [59],
    "Тра": [51],
    "Чер": [45],
    "Лип": [41],
    "Сер": [43],
    "Вер": [53],
    "Жов": [67],
    "Лис": [77],
    "Гру": [83],
})

wide

  місто  Січ  Лют  Бер  Кві  Тра  Чер  Лип  Сер  Вер  Жов  Лис  Гру
0  Суми   79   75   69   59   51   45   41   43   53   67   77   83

In [2]:
tidy = wide.melt(
    id_vars="місто",
    var_name="місяць",
    value_name="хмарність"
)

tidy

   місто місяць  хмарність
0   Суми    Січ         79
1   Суми    Лют         75
2   Суми    Бер         69
3   Суми    Кві         59
4   Суми    Тра         51
5   Суми    Чер         45
6   Суми    Лип         41
7   Суми    Сер         43
8   Суми    Вер         53
9   Суми    Жов         67
10  Суми    Лис         77
11  Суми    Гру         83

In [3]:
tidy.shape

(12, 3)

### Шкали вимірювання

- **місто** — номінальна шкала, оскільки назви міст є категоріями без числового порядку.
- **місяць** — номінальна шкала, оскільки назви місяців використовуються як категоріальні позначення.
- **хмарність** — шкала відношень, оскільки вимірюється у відсотках і має природний нуль: 0% означає відсутність хмарності.

In [4]:
back = tidy.pivot(
    index="місто",
    columns="місяць",
    values="хмарність"
)

back

місяць  Бер  Вер  Гру  Жов  Кві  Лип  Лис  Лют  Сер  Січ  Тра  Чер
місто
Суми     69   53   83   67   59   41   77   75   43   79   51   45

In [5]:
back_sorted = back.reindex(columns=wide.columns[1:])
back_sorted

       Січ  Лют  Бер  Кві  Тра  Чер  Лип  Сер  Вер  Жов  Лис  Гру
місто
Суми    79   75   69   59   51   45   41   43   53   67   77   83

In [6]:
back_sorted.equals(wide.set_index("місто"))

True

In [7]:
tidy.to_csv("variant.csv", index=False)

reloaded_csv = pd.read_csv("variant.csv")

reloaded_csv

   місто місяць  хмарність
0   Суми    Січ         79
1   Суми    Лют         75
2   Суми    Бер         69
3   Суми    Кві         59
4   Суми    Тра         51
5   Суми    Чер         45
6   Суми    Лип         41
7   Суми    Сер         43
8   Суми    Вер         53
9   Суми    Жов         67
10  Суми    Лис         77
11  Суми    Гру         83

In [8]:
reloaded_csv.equals(tidy)

True

In [9]:
tidy.to_json(
    "variant.json",
    orient="records",
    force_ascii=False
)

reloaded_json = pd.read_json("variant.json")

reloaded_json

   місто місяць  хмарність
0   Суми    Січ         79
1   Суми    Лют         75
2   Суми    Бер         69
3   Суми    Кві         59
4   Суми    Тра         51
5   Суми    Чер         45
6   Суми    Лип         41
7   Суми    Сер         43
8   Суми    Вер         53
9   Суми    Жов         67
10  Суми    Лис         77
11  Суми    Гру         83

In [10]:
reloaded_json.equals(tidy)

True

In [11]:
print("CSV:")
print(open("variant.csv", encoding="utf-8").read())

print("\nJSON:")
print(open("variant.json", encoding="utf-8").read())

CSV:
місто,місяць,хмарність
Суми,Січ,79
Суми,Лют,75
Суми,Бер,69
Суми,Кві,59
Суми,Тра,51
Суми,Чер,45
Суми,Лип,41
Суми,Сер,43
Суми,Вер,53
Суми,Жов,67
Суми,Лис,77
Суми,Гру,83


JSON:
[{"місто":"Суми","місяць":"Січ","хмарність":79},{"місто":"Суми","місяць":"Лют","хмарність":75},{"місто":"Суми","місяць":"Бер","хмарність":69},{"місто":"Суми","місяць":"Кві","хмарність":59},{"місто":"Суми","місяць":"Тра","хмарність":51},{"місто":"Суми","місяць":"Чер","хмарність":45},{"місто":"Суми","місяць":"Лип","хмарність":41},{"місто":"Суми","місяць":"Сер","хмарність":43},{"місто":"Суми","місяць":"Вер","хмарність":53},{"місто":"Суми","місяць":"Жов","хмарність":67},{"місто":"Суми","місяць":"Лис","хмарність":77},{"місто":"Суми","місяць":"Гру","хмарність":83}]

# Практика 3. Приведення до tidy data

**Варіант:** 9  
**Місто:** Суми  
**Студент:** Коць Артем  
**Група:** ІТ-42

## Письмові відповіді

### 1. Чому "місто" — номінальна шкала, а "хмарність" — шкала відношень?

"Місто" є номінальною шкалою, тому що це назва категорії, між якими немає числового порядку. "Хмарність" є шкалою відношень, тому що вона вимірюється у відсотках і має природний нуль — 0% означає відсутність хмарності.

### 2. Чому wide-таблиця не є tidy?

У wide-таблиці місяці розміщені в окремих стовпцях, тому одна змінна "місяць" фактично розподілена між багатьма стовпцями. Після `melt()` усі місяці перетворюються на значення одного стовпця "місяць", а значення хмарності — на стовпець "хмарність". Кожен рядок після цього описує одне спостереження.

### 3. Чим CSV відрізняється від JSON?

CSV зберігає таблицю у вигляді рядків і стовпців, розділених спеціальним символом. JSON зберігає дані у структурованому форматі об'єктів і масивів. Для цієї таблиці CSV є простішим табличним представленням, а JSON — більш структурованим форматом, який зручно використовувати для обміну даними між програмами.