# Практика 4. Чищення набору даних

**Варіант:** 9  
**Місто:** Суми  
**Базова ціна:** 730 грн  
**Базова кількість:** 2  
**Студент:** Коць Артем  
**Група:** ІТ-42

In [1]:
import numpy as np
import pandas as pd

In [2]:
orders = pd.DataFrame([
    {"дата": "2026-09-01", "місто": "Суми",      "товар": "Ноутбук", "ціна": 730,        "кількість": 2},
    {"дата": "2026-09-02", "місто": " Суми ",   "товар": "Ноутбук", "ціна": "730 грн",   "кількість": 3},
    {"дата": "2026-09-03", "місто": "СУМИ",     "товар": "Ноутбук", "ціна": 730,        "кількість": np.nan},
    {"дата": "2026-09-04", "місто": "Суми",     "товар": "Ноутбук", "ціна": "730 грн",   "кількість": 1},
    {"дата": "2026-09-05", "місто": " Суми ",   "товар": "Ноутбук", "ціна": 730,        "кількість": np.nan},
    {"дата": "2026-09-06", "місто": "СУМИ",     "товар": "Ноутбук", "ціна": 730,        "кількість": 4},
    {"дата": "2026-09-07", "місто": "Суми",     "товар": "Ноутбук", "ціна": 7300,       "кількість": 2},
    {"дата": "2026-09-02", "місто": " Суми ",   "товар": "Ноутбук", "ціна": "730 грн",   "кількість": 3},
])

orders

         дата   місто    товар     ціна  кількість
0  2026-09-01    Суми  Ноутбук      730        2.0
1  2026-09-02   Суми   Ноутбук  730 грн        3.0
2  2026-09-03    СУМИ  Ноутбук      730        NaN
3  2026-09-04    Суми  Ноутбук  730 грн        1.0
4  2026-09-05   Суми   Ноутбук      730        NaN
5  2026-09-06    СУМИ  Ноутбук      730        4.0
6  2026-09-07    Суми  Ноутбук     7300        2.0
7  2026-09-02   Суми   Ноутбук  730 грн        3.0

In [3]:
orders.isna().sum()

дата         0
місто        0
товар        0
ціна         0
кількість    2
dtype: int64

In [4]:
median_quantity = orders["кількість"].median()

orders["кількість"] = orders["кількість"].fillna(median_quantity)

orders

         дата   місто    товар     ціна  кількість
0  2026-09-01    Суми  Ноутбук      730        2.0
1  2026-09-02   Суми   Ноутбук  730 грн        3.0
2  2026-09-03    СУМИ  Ноутбук      730        2.5
3  2026-09-04    Суми  Ноутбук  730 грн        1.0
4  2026-09-05   Суми   Ноутбук      730        2.5
5  2026-09-06    СУМИ  Ноутбук      730        4.0
6  2026-09-07    Суми  Ноутбук     7300        2.0
7  2026-09-02   Суми   Ноутбук  730 грн        3.0

### Чому медіана доречніша за середнє?

Медіана є доречнішою для цього набору, оскільки маємо лише 8 спостережень і в даних може бути велике або нетипове значення. Медіана менш чутлива до викидів, ніж середнє, тому дозволяє стабільніше заповнити пропущені значення кількості.

In [5]:
orders.duplicated().sum()

np.int64(1)

In [6]:
orders = orders.drop_duplicates()

print("Кількість рядків після видалення дубліката:", len(orders))
orders

Кількість рядків після видалення дубліката: 7

         дата   місто    товар     ціна  кількість
0  2026-09-01    Суми  Ноутбук      730        2.0
1  2026-09-02   Суми   Ноутбук  730 грн        3.0
2  2026-09-03    СУМИ  Ноутбук      730        2.5
3  2026-09-04    Суми  Ноутбук  730 грн        1.0
4  2026-09-05   Суми   Ноутбук      730        2.5
5  2026-09-06    СУМИ  Ноутбук      730        4.0
6  2026-09-07    Суми  Ноутбук     7300        2.0

In [7]:
orders["ціна"] = (
    orders["ціна"]
    .astype(str)
    .str.replace(" грн", "", regex=False)
    .astype(float)
)

orders.dtypes

дата             str
місто            str
товар            str
ціна         float64
кількість    float64
dtype: object

In [8]:
orders["місто"] = (
    orders["місто"]
    .str.strip()
    .str.lower()
    .replace({"суми": "Суми"})
)

orders["місто"].unique()

<StringArray>
['Суми']
Length: 1, dtype: str

In [9]:
q1, q3 = orders["ціна"].quantile([0.25, 0.75])

iqr = q3 - q1

lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr

print("Q1 =", q1)
print("Q3 =", q3)
print("IQR =", iqr)
print("Нижня межа =", lower)
print("Верхня межа =", upper)

Q1 = 730.0
Q3 = 730.0
IQR = 0.0
Нижня межа = 730.0
Верхня межа = 730.0

In [10]:
outliers = orders[
    (orders["ціна"] < lower) |
    (orders["ціна"] > upper)
]

outliers

         дата місто    товар    ціна  кількість
6  2026-09-07  Суми  Ноутбук  7300.0        2.0

In [11]:
orders.loc[orders["ціна"] == 7300, "ціна"] = 730

orders

         дата місто    товар   ціна  кількість
0  2026-09-01  Суми  Ноутбук  730.0        2.0
1  2026-09-02  Суми  Ноутбук  730.0        3.0
2  2026-09-03  Суми  Ноутбук  730.0        2.5
3  2026-09-04  Суми  Ноутбук  730.0        1.0
4  2026-09-05  Суми  Ноутбук  730.0        2.5
5  2026-09-06  Суми  Ноутбук  730.0        4.0
6  2026-09-07  Суми  Ноутбук  730.0        2.0

In [12]:
print("Пропуски:")
print(orders.isna().sum())

print("\nДублікати:")
print(orders.duplicated().sum())

print("\nТипи даних:")
print(orders.dtypes)

print("\nУнікальні міста:")
print(orders["місто"].unique())

print("\nКількість рядків:", len(orders))

Пропуски:
дата         0
місто        0
товар        0
ціна         0
кількість    0
dtype: int64

Дублікати:
0

Типи даних:
дата             str
місто            str
товар            str
ціна         float64
кількість    float64
dtype: object

Унікальні міста:
<StringArray>
['Суми']
Length: 1, dtype: str

Кількість рядків: 7

## Підсумкові письмові відповіді

### 1. Чому заповнення пропуску середнім може спотворити стандартне відхилення?

Якщо замінювати пропуски середнім значенням, кілька спостережень отримують однакове центральне значення. Це може штучно зменшити розкид даних і стандартне відхилення. Медіана є стійкішою до нетипових значень і тому добре підходить для невеликого набору даних.

### 2. Чим відрізняється duplicated() без subset і з subset?

`duplicated()` без `subset` перевіряє повний збіг усіх значень рядка. `duplicated(subset=[...])` перевіряє дублікати лише за вказаними стовпцями. Тому результати можуть відрізнятися.

### 3. Чому не можна автоматично видаляти всі значення поза межами IQR?

Значення поза межами IQR не обов'язково є помилками. Вони можуть бути реальними рідкісними спостереженнями або великими замовленнями. Тому IQR використовується для виявлення підозрілих значень, а рішення про їх видалення або виправлення потрібно приймати після аналізу даних.