In [1]:
import numpy as np
import pandas as pd

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)

NumPy: 2.5.3
Pandas: 3.0.6

In [2]:
humidity = pd.Series(
    [84, 82, 78, 70, 65, 63, 61, 63, 68, 75, 81, 85],
    name="Вологість, %"
)

humidity

0     84
1     82
2     78
3     70
4     65
5     63
6     61
7     63
8     68
9     75
10    81
11    85
Name: Вологість, %, dtype: int64

In [3]:
humidity.describe()

count    12.000000
mean     72.916667
std       8.948929
min      61.000000
25%      64.500000
50%      72.500000
75%      81.250000
max      85.000000
Name: Вологість, %, dtype: float64

In [5]:
rozmakh = humidity.max() - humidity.min()
variance_sample = humidity.var(ddof=1)
variance_population = humidity.var(ddof=0)
std = humidity.std()
q1 = humidity.quantile(0.25)
q3 = humidity.quantile(0.75)
iqr = q3 - q1
cv = std / humidity.mean() * 100

print("Розмах:", rozmakh)
print("Дисперсія (ddof=1):", variance_sample)
print("Дисперсія (ddof=0):", variance_population)
print("Стандартне відхилення:", std)
print("Q1:", q1)
print("Q3:", q3)
print("IQR:", iqr)
print("CV (%):", cv)

Розмах: 24
Дисперсія (ddof=1): 80.08333333333334
Дисперсія (ddof=0): 73.40972222222223
Стандартне відхилення: 8.9489291724392
Q1: 64.5
Q3: 81.25
IQR: 16.75
CV (%): 12.27281715077376



count — кількість спостережень.

mean — середнє арифметичне, міра положення.

std — стандартне відхилення, міра розсіювання.

min — мінімальне значення.

25% — перший квартиль (Q1), міра положення.

50% — медіана (Q2), міра положення.

75% — третій квартиль (Q3), міра положення.

max — максимальне значення.

In [6]:
print("Q1 з describe():", humidity.describe()["25%"])
print("Q1 вручну:", q1)
print("Q3 з describe():", humidity.describe()["75%"])
print("Q3 вручну:", q3)

Q1 з describe(): 64.5
Q1 вручну: 64.5
Q3 з describe(): 81.25
Q3 вручну: 81.25

In [7]:
df = pd.DataFrame({
    "Місто": [
        "Kyiv", "Lviv", "Odesa", "Kharkiv", "Dnipro",
        "Chernihiv", "Ivano-Frankivsk", "Poltava", "Sumy", "Uzhhorod"
    ],
    "Регіон": [
        "Центр", "Захід", "Південь", "Схід", "Схід",
        "Центр", "Захід", "Центр", "Схід", "Захід"
    ],
    "Січень": [84, 85, 82, 83, 82, 85, 86, 84, 85, 84],
    "Лютий": [82, 83, 80, 80, 79, 83, 84, 81, 82, 82],
    "Березень": [78, 80, 78, 75, 74, 79, 81, 76, 77, 79],
    "Квітень": [70, 73, 74, 68, 67, 71, 75, 69, 70, 73],
    "Травень": [65, 68, 71, 62, 61, 66, 70, 63, 64, 68],
    "Червень": [63, 65, 69, 60, 59, 63, 67, 61, 62, 66],
    "Липень": [61, 63, 67, 58, 57, 61, 65, 59, 60, 64],
    "Серпень": [63, 65, 68, 60, 59, 63, 67, 61, 62, 66],
    "Вересень": [68, 70, 72, 66, 65, 69, 72, 67, 68, 71],
    "Жовтень": [75, 77, 76, 73, 72, 76, 78, 74, 75, 77],
    "Листопад": [81, 82, 80, 79, 78, 82, 83, 80, 81, 82],
    "Грудень": [85, 86, 83, 84, 83, 86, 87, 85, 86, 85]
})

df

,Місто,Регіон,Січень,Лютий,Березень,Квітень,Травень,Червень,Липень,Серпень,Вересень,Жовтень,Листопад,Грудень
0,Kyiv,Центр,84,82,78,70,65,63,61,63,68,75,81,85
1,Lviv,Захід,85,83,80,73,68,65,63,65,70,77,82,86
2,Odesa,Південь,82,80,78,74,71,69,67,68,72,76,80,83
3,Kharkiv,Схід,83,80,75,68,62,60,58,60,66,73,79,84
4,Dnipro,Схід,82,79,74,67,61,59,57,59,65,72,78,83
5,Chernihiv,Центр,85,83,79,71,66,63,61,63,69,76,82,86
6,Ivano-Frankivsk,Захід,86,84,81,75,70,67,65,67,72,78,83,87
7,Poltava,Центр,84,81,76,69,63,61,59,61,67,74,80,85
8,Sumy,Схід,85,82,77,70,64,62,60,62,68,75,81,86
9,Uzhhorod,Захід,84,82,79,73,68,66,64,66,71,77,82,85

In [8]:
months = [
    "Січень", "Лютий", "Березень", "Квітень",
    "Травень", "Червень", "Липень", "Серпень",
    "Вересень", "Жовтень", "Листопад", "Грудень"
]

df["Середня за рік"] = df[months].mean(axis=1)

df[["Місто", "Регіон", "Середня за рік"]]

             Місто   Регіон  Середня за рік
0             Kyiv    Центр       72.916667
1             Lviv    Захід       74.750000
2            Odesa  Південь       75.000000
3          Kharkiv     Схід       70.666667
4           Dnipro     Схід       69.666667
5        Chernihiv    Центр       73.666667
6  Ivano-Frankivsk    Захід       76.250000
7          Poltava    Центр       71.666667
8             Sumy     Схід       72.666667
9         Uzhhorod    Захід       74.750000

In [9]:
center = df[df["Регіон"] == "Центр"]["Середня за рік"]

center.describe()

count     3.000000
mean     72.750000
std       1.010363
min      71.666667
25%      72.291667
50%      72.916667
75%      73.291667
max      73.666667
Name: Середня за рік, dtype: float64

In [10]:
west = df[df["Регіон"] == "Захід"]["Середня за рік"]

west.describe()

count     3.000000
mean     75.250000
std       0.866025
min      74.750000
25%      74.750000
50%      74.750000
75%      75.500000
max      76.250000
Name: Середня за рік, dtype: float64

In [11]:
print("Центр:")
print(center.describe())

print("\nЗахід:")
print(west.describe())

Центр:
count     3.000000
mean     72.750000
std       1.010363
min      71.666667
25%      72.291667
50%      72.916667
75%      73.291667
max      73.666667
Name: Середня за рік, dtype: float64

Захід:
count     3.000000
mean     75.250000
std       0.866025
min      74.750000
25%      74.750000
50%      74.750000
75%      75.500000
max      76.250000
Name: Середня за рік, dtype: float64

Для Центрального регіону середнє значення середньої річної вологості становить 72,75%, а стандартне відхилення — 1,01. Коефіцієнт варіації становить приблизно 1,39%.

Для Західного регіону середнє значення становить 75,25%, а стандартне відхилення — 0,87. Коефіцієнт варіації становить приблизно 1,15%.

Отже, стандартне відхилення більше у Центральному регіоні, і коефіцієнт варіації також більший у Центральному регіоні. Тому обидва показники узгоджуються: відносна варіативність середньої річної вологості в Центральному регіоні дещо більша.

In [12]:
humidity = pd.Series(
    [86, 84, 81, 75, 70, 67, 65, 67, 72, 78, 83, 87],
    name="Вологість"
)

mean = humidity.mean()
median = humidity.median()

print(f"Середнє: {mean:.2f}")
print(f"Медіана: {median:.2f}")
print(f"Різниця між середнім і медіаною: {abs(mean - median):.2f}")

Середнє: 76.25
Медіана: 76.50
Різниця між середнім і медіаною: 0.25

In [13]:
humidity = pd.Series(
    [86, 84, 81, 75, 70, 67, 65, 67, 72, 78, 83, 87],
    name="Вологість"
)

mean = humidity.mean()
median = humidity.median()

print(f"Середнє: {mean:.2f}")
print(f"Медіана: {median:.2f}")
print(f"Різниця між середнім і медіаною: {abs(mean - median):.2f}")

Середнє: 76.25
Медіана: 76.50
Різниця між середнім і медіаною: 0.25

За отриманими результатами середнє значення вологості становить 76,25%, а медіана — 76,50%. Різниця між ними становить лише 0,25 процентного пункта. Оскільки середнє та медіана мають дуже близькі значення, розподіл 12 місячних значень вологості Івано-Франківська можна вважати близьким до симетричного, без вираженої скошеності.

Для цих даних середнє значення є репрезентативною мірою положення, оскільки значення не мають сильної скошеності та середнє практично не відрізняється від медіани. Медіана також добре характеризує центр розподілу, але суттєвої переваги над середнім у цьому випадку немає.

In [14]:
kharkiv = pd.Series(
    [83, 80, 75, 68, 62, 60, 58, 60, 66, 73, 79, 84],
    name="Вологість Харків"
)

kharkiv_mean = kharkiv.mean()
kharkiv_std = kharkiv.std()
kharkiv_cv = kharkiv_std / kharkiv_mean * 100

print(f"Середня вологість Харкова: {kharkiv_mean:.2f}%")
print(f"Стандартне відхилення Харкова: {kharkiv_std:.2f}")
print(f"Коефіцієнт варіації Харкова: {kharkiv_cv:.2f}%")

Середня вологість Харкова: 70.67%
Стандартне відхилення Харкова: 9.55
Коефіцієнт варіації Харкова: 13.51%

In [15]:
ivano_mean = humidity.mean()
ivano_std = humidity.std()
ivano_cv = ivano_std / ivano_mean * 100

print(f"Середня вологість Івано-Франківська: {ivano_mean:.2f}%")
print(f"Стандартне відхилення Івано-Франківська: {ivano_std:.2f}")
print(f"Коефіцієнт варіації Івано-Франківська: {ivano_cv:.2f}%")

print(f"\nКоефіцієнт варіації Харкова: {kharkiv_cv:.2f}%")

Середня вологість Івано-Франківська: 76.25%
Стандартне відхилення Івано-Франківська: 7.97
Коефіцієнт варіації Івано-Франківська: 10.45%

Коефіцієнт варіації Харкова: 13.51%

Для порівняння було обрано Харків, який належить до Східного регіону, тоді як Івано-Франківськ належить до Західного.

Коефіцієнт варіації Івано-Франківська становить приблизно 10,45%, а Харкова — приблизно 13,51%. Отже, відносний розкид значень вологості у Харкова більший.

Коефіцієнт варіації є коректнішим інструментом для порівняння варіативності, оскільки він враховує величину середнього значення і показує стандартне відхилення у відсотках від середнього. Сирий std показує абсолютний розкид і не враховує масштаб даних. Навіть якщо середні значення вологості двох міст близькі, CV дає стандартизовану міру варіативності, тому його використання робить порівняння зрозумілішим.



**1. Чи можете пояснити, яка міра розсіювання з лекції стоїть за кожним із рядків `std`, `25%`/`75%` і `min`/`max` у `.describe()`?**

`std` — це стандартне відхилення, яке показує середній рівень розсіювання значень відносно їхнього середнього. `25%` і `75%` — це перший та третій квартилі (Q1 і Q3), які використовуються для визначення міжквартильного розмаху IQR = Q3 − Q1. `min` і `max` — мінімальне та максимальне значення, за якими можна визначити розмах: max − min.

**2. Чому заповнення пропуску середнім штучно зменшує `std`?**

Якщо пропущене значення замінити середнім, воно потрапляє точно в центр розподілу і не збільшує відхилення від середнього. Через це розкид даних стає меншим, а стандартне відхилення може штучно зменшитися. Тому таке заповнення може створювати хибне враження про меншу варіативність даних.

**3. Чому порівнювати абсолютні значення `std` двох груп без коефіцієнта варіації може привести до хибного висновку?**

Стандартне відхилення показує абсолютний розкид і залежить від масштабу значень. Тому дві групи з різними середніми можуть мати різні значення `std`, які не можна коректно порівнювати лише за абсолютною величиною. Коефіцієнт варіації (`std / mean × 100%`) показує розкид відносно середнього і тому зручніший для порівняння варіативності.

**4. Судячи з власного розподілу, чи він симетричний, і яка міра положення репрезентативніша?**

Для Івано-Франківська середнє значення вологості становить 76,25%, а медіана — 76,50%. Різниця між ними лише 0,25 процентного пункта, тому розподіл можна вважати близьким до симетричного, без вираженої скошеності. Для цих даних середнє є репрезентативною мірою положення, оскільки воно майже не відрізняється від медіани і сильних викидів немає.