Письмові відповіді
1. Чому .loc[1:6] і .iloc[0:6] можуть повернути різну кількість рядків?

.loc вибирає рядки за значеннями індексу, тобто за їхніми підписами. .iloc вибирає рядки за їхньою позицією в таблиці. Наприклад, .loc[1:6] вибирає рядки з індексами від 1 до 6 включно, а .iloc[0:6] вибирає перші 6 рядків із позиціями від 0 до 5. Якщо індекс таблиці не збігається з позиціями рядків, результати можуть бути різними.

2. Чому and викликає помилку, а & — ні?

У pandas умови df["avg_temp"] > 10 та df["precip"] > 50 повертають набір значень True або False для кожного рядка. Оператор and призначений для звичайних одиничних логічних значень, тому він не може правильно обробити два стовпці pandas і викликає помилку. Оператор & виконує поелементне логічне «І», тому для об'єднання умов у pandas потрібно використовувати саме &. Кожну умову також потрібно брати в дужки.

3. У чому різниця між обчислюваним стовпцем через формулу та через .apply()?

Стовпець, створений формулою, обчислюється за допомогою векторизованих операцій одразу для всіх значень стовпця. Наприклад, температуру у Фаренгейтах можна отримати за формулою df["avg_temp"] * 9 / 5 + 32. Метод .apply() дозволяє застосувати власну функцію до кожного значення. Він зручний для складнішої логіки, наприклад для визначення пори року за номером місяця.

In [22]:
df

   month  avg_temp  precip  avg_temp_f  is_wet season
1    Січ        -3      38        26.6   False   зима
2    Лют        -2      36        28.4   False   зима
3    Бер         2      38        35.6   False  весна
4    Кві         9      41        48.2   False  весна
5    Тра        15      53        59.0    True  весна
6    Чер        19      74        66.2    True   літо
7    Лип        21      84        69.8    True   літо
8    Сер        20      69        68.0    True   літо
9    Вер        15      47        59.0   False  осінь
10   Жов         9      36        48.2   False  осінь
11   Лис         3      44        37.4   False  осінь
12   Гру        -1      44        30.2   False   зима

In [21]:
df["season"] = df.index.to_series().apply(get_season)
df

   month  avg_temp  precip  avg_temp_f  is_wet season
1    Січ        -3      38        26.6   False   зима
2    Лют        -2      36        28.4   False   зима
3    Бер         2      38        35.6   False  весна
4    Кві         9      41        48.2   False  весна
5    Тра        15      53        59.0    True  весна
6    Чер        19      74        66.2    True   літо
7    Лип        21      84        69.8    True   літо
8    Сер        20      69        68.0    True   літо
9    Вер        15      47        59.0   False  осінь
10   Жов         9      36        48.2   False  осінь
11   Лис         3      44        37.4   False  осінь
12   Гру        -1      44        30.2   False   зима

In [20]:
def get_season(month_number):
    if month_number in [12, 1, 2]:
        return "зима"
    elif month_number in [3, 4, 5]:
        return "весна"
    elif month_number in [6, 7, 8]:
        return "літо"
    else:
        return "осінь"

In [19]:
df["is_wet"] = df["precip"] > df["precip"].mean()
df

   month  avg_temp  precip  avg_temp_f  is_wet
1    Січ        -3      38        26.6   False
2    Лют        -2      36        28.4   False
3    Бер         2      38        35.6   False
4    Кві         9      41        48.2   False
5    Тра        15      53        59.0    True
6    Чер        19      74        66.2    True
7    Лип        21      84        69.8    True
8    Сер        20      69        68.0    True
9    Вер        15      47        59.0   False
10   Жов         9      36        48.2   False
11   Лис         3      44        37.4   False
12   Гру        -1      44        30.2   False

In [18]:
df["avg_temp_f"] = df["avg_temp"] * 9 / 5 + 32
df

   month  avg_temp  precip  avg_temp_f
1    Січ        -3      38        26.6
2    Лют        -2      36        28.4
3    Бер         2      38        35.6
4    Кві         9      41        48.2
5    Тра        15      53        59.0
6    Чер        19      74        66.2
7    Лип        21      84        69.8
8    Сер        20      69        68.0
9    Вер        15      47        59.0
10   Жов         9      36        48.2
11   Лис         3      44        37.4
12   Гру        -1      44        30.2

Завдання 4

In [17]:
df.loc[
    (df["avg_temp"] < 0) | (df["precip"] > 80),
    "month"
]

1     Січ
2     Лют
7     Лип
12    Гру
Name: month, dtype: str

In [16]:
df.loc[
    (df["avg_temp"] > 10) & (df["precip"] > 50),
    "month"
]

5    Тра
6    Чер
7    Лип
8    Сер
Name: month, dtype: str

In [15]:
df.loc[df["avg_temp"] > 15, "month"]

6    Чер
7    Лип
8    Сер
Name: month, dtype: str

Завдання 3

In [14]:
df[["month", "precip"]]

   month  precip
1    Січ      38
2    Лют      36
3    Бер      38
4    Кві      41
5    Тра      53
6    Чер      74
7    Лип      84
8    Сер      69
9    Вер      47
10   Жов      36
11   Лис      44
12   Гру      44

In [13]:
df.iloc[0:6, 1]

1    -3
2    -2
3     2
4     9
5    15
6    19
Name: avg_temp, dtype: int64

In [12]:
df.loc[1:6, "avg_temp"]

1    -3
2    -2
3     2
4     9
5    15
6    19
Name: avg_temp, dtype: int64

In [11]:
df.index = range(1, 13)
df

   month  avg_temp  precip
1    Січ        -3      38
2    Лют        -2      36
3    Бер         2      38
4    Кві         9      41
5    Тра        15      53
6    Чер        19      74
7    Лип        21      84
8    Сер        20      69
9    Вер        15      47
10   Жов         9      36
11   Лис         3      44
12   Гру        -1      44

Завдання 2

In [10]:
df = df_by_month.reset_index()
df

   month  avg_temp  precip
0    Січ        -3      38
1    Лют        -2      36
2    Бер         2      38
3    Кві         9      41
4    Тра        15      53
5    Чер        19      74
6    Лип        21      84
7    Сер        20      69
8    Вер        15      47
9    Жов         9      36
10   Лис         3      44
11   Гру        -1      44

In [9]:
df_by_month.loc["Тра"]

avg_temp    15
precip      53
Name: Тра, dtype: int64

In [8]:
df_by_month = df.set_index("month")
df_by_month

       avg_temp  precip
month
Січ          -3      38
Лют          -2      36
Бер           2      38
Кві           9      41
Тра          15      53
Чер          19      74
Лип          21      84
Сер          20      69
Вер          15      47
Жов           9      36
Лис           3      44
Гру          -1      44

In [7]:
df.index

RangeIndex(start=0, stop=12, step=1)

In [6]:
df

   month  avg_temp  precip
0    Січ        -3      38
1    Лют        -2      36
2    Бер         2      38
3    Кві         9      41
4    Тра        15      53
5    Чер        19      74
6    Лип        21      84
7    Сер        20      69
8    Вер        15      47
9    Жов         9      36
10   Лис         3      44
11   Гру        -1      44

Завдання 1

In [5]:
df.dtypes

month         str
avg_temp    int64
precip      int64
dtype: object

In [4]:
df.shape

(12, 3)

In [3]:
df.head()

  month  avg_temp  precip
0   Січ        -3      38
1   Лют        -2      36
2   Бер         2      38
3   Кві         9      41
4   Тра        15      53

In [2]:
months = ["Січ", "Лют", "Бер", "Кві", "Тра", "Чер",
          "Лип", "Сер", "Вер", "Жов", "Лис", "Гру"]

avg_temp = [-3, -2, 2, 9, 15, 19, 21, 20, 15, 9, 3, -1]

precip = [38, 36, 38, 41, 53, 74, 84, 69, 47, 36, 44, 44]

df = pd.DataFrame({
    "month": months,
    "avg_temp": avg_temp,
    "precip": precip
})

df

   month  avg_temp  precip
0    Січ        -3      38
1    Лют        -2      36
2    Бер         2      38
3    Кві         9      41
4    Тра        15      53
5    Чер        19      74
6    Лип        21      84
7    Сер        20      69
8    Вер        15      47
9    Жов         9      36
10   Лис         3      44
11   Гру        -1      44

In [1]:
import pandas as pd