# Практика 4. Чищення набору даних

**Студент:** Nazar_Pryimachuk  
**Група:** IT-42  
**Варіант:** 7  
**Місто:** Івано-Франківськ  
**Базова ціна:** 760 грн  
**Базова кількість:** 3

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
## Завдання 1. Побудова брудного набору

In [3]:
orders = pd.DataFrame([
    {
        "id": 1,
        "дата": "2026-09-01",
        "товар": "Product 7",
        "місто": "Івано-Франківськ",
        "ціна": 760,
        "кількість": 3
    },
    {
        "id": 2,
        "дата": "2026-09-02",
        "товар": "Product 7",
        "місто": " Івано-Франківськ ",
        "ціна": "760 грн",
        "кількість": 4
    },
    {
        "id": 3,
        "дата": "2026-09-03",
        "товар": "Product 7",
        "місто": "ІВАНО-ФРАНКІВСЬК",
        "ціна": 760,
        "кількість": np.nan
    },
    {
        "id": 4,
        "дата": "2026-09-04",
        "товар": "Product 7",
        "місто": "Івано-Франківськ",
        "ціна": "760 грн",
        "кількість": 2
    },
    {
        "id": 5,
        "дата": "2026-09-05",
        "товар": "Product 7",
        "місто": "Івано-Франківськ",
        "ціна": 760,
        "кількість": np.nan
    },
    {
        "id": 6,
        "дата": "2026-09-06",
        "товар": "Product 7",
        "місто": "Івано-Франківськ",
        "ціна": 7600,
        "кількість": 3
    },
    {
        "id": 7,
        "дата": "2026-09-07",
        "товар": "Product 7",
        "місто": "Івано-Франківськ",
        "ціна": 760,
        "кількість": 5
    },
    {
        "id": 7,
        "дата": "2026-09-07",
        "товар": "Product 7",
        "місто": "Івано-Франківськ",
        "ціна": 760,
        "кількість": 5
    }
])

orders

   id        дата      товар               місто     ціна  кількість
0   1  2026-09-01  Product 7    Івано-Франківськ      760        3.0
1   2  2026-09-02  Product 7   Івано-Франківськ   760 грн        4.0
2   3  2026-09-03  Product 7    ІВАНО-ФРАНКІВСЬК      760        NaN
3   4  2026-09-04  Product 7    Івано-Франківськ  760 грн        2.0
4   5  2026-09-05  Product 7    Івано-Франківськ      760        NaN
5   6  2026-09-06  Product 7    Івано-Франківськ     7600        3.0
6   7  2026-09-07  Product 7    Івано-Франківськ      760        5.0
7   7  2026-09-07  Product 7    Івано-Франківськ      760        5.0

## Завдання 2. Виявлення та заповнення пропусків

In [7]:
missing = orders.isna().sum()

print("Кількість пропусків у кожному стовпці:")
print(missing)

median_quantity = orders["кількість"].median()

print("Медіана кількості:", median_quantity)

Кількість пропусків у кожному стовпці:
id           0
дата         0
товар        0
місто        0
ціна         0
кількість    2
dtype: int64
Медіана кількості: 3.5

In [8]:
orders["кількість"] = orders["кількість"].fillna(median_quantity)

print("Пропуски після заповнення:")
print(orders["кількість"].isna().sum())

orders

Пропуски після заповнення:
0

   id        дата      товар               місто     ціна  кількість
0   1  2026-09-01  Product 7    Івано-Франківськ      760        3.0
1   2  2026-09-02  Product 7   Івано-Франківськ   760 грн        4.0
2   3  2026-09-03  Product 7    ІВАНО-ФРАНКІВСЬК      760        3.5
3   4  2026-09-04  Product 7    Івано-Франківськ  760 грн        2.0
4   5  2026-09-05  Product 7    Івано-Франківськ      760        3.5
5   6  2026-09-06  Product 7    Івано-Франківськ     7600        3.0
6   7  2026-09-07  Product 7    Івано-Франківськ      760        5.0
7   7  2026-09-07  Product 7    Івано-Франківськ      760        5.0

In [9]:
print("Кількість повних дублікатів:")
print(orders.duplicated().sum())

Кількість повних дублікатів:
1

In [10]:
print("Дублікати за id:")
print(orders.duplicated(subset=["id"]).sum())

Дублікати за id:
1

In [11]:
orders = orders.drop_duplicates(subset=["id"])

print("Кількість рядків після видалення дубліката:", len(orders))

orders

Кількість рядків після видалення дубліката: 7

   id        дата      товар               місто     ціна  кількість
0   1  2026-09-01  Product 7    Івано-Франківськ      760        3.0
1   2  2026-09-02  Product 7   Івано-Франківськ   760 грн        4.0
2   3  2026-09-03  Product 7    ІВАНО-ФРАНКІВСЬК      760        3.5
3   4  2026-09-04  Product 7    Івано-Франківськ  760 грн        2.0
4   5  2026-09-05  Product 7    Івано-Франківськ      760        3.5
5   6  2026-09-06  Product 7    Івано-Франківськ     7600        3.0
6   7  2026-09-07  Product 7    Івано-Франківськ      760        5.0

### Різниця між duplicated() без subset і з subset

Метод duplicated() без параметра subset перевіряє повний збіг усіх значень рядка. Якщо всі значення двох рядків однакові, другий рядок визначається як дублікат.

Метод duplicated() з subset перевіряє тільки вказані стовпці. У цій роботі для визначення унікального замовлення використано поле "id". Тому два рядки з однаковим id вважаються дубльованими.

In [12]:
print(orders.dtypes)

id             int64
дата             str
товар            str
місто            str
ціна          object
кількість    float64
dtype: object

In [13]:
orders["ціна"] = (
    orders["ціна"]
    .astype(str)
    .str.replace(" грн", "", regex=False)
    .astype(float)
)

print(orders.dtypes)

id             int64
дата             str
товар            str
місто            str
ціна         float64
кількість    float64
dtype: object

In [14]:
print("Варіанти назви міста:")
print(orders["місто"].unique())

Варіанти назви міста:
<StringArray>
['Івано-Франківськ', ' Івано-Франківськ ', 'ІВАНО-ФРАНКІВСЬК']
Length: 3, dtype: str

In [15]:
city_mapping = {
    "Івано-Франківськ": "Івано-Франківськ",
    " Івано-Франківськ ": "Івано-Франківськ",
    "ІВАНО-ФРАНКІВСЬК": "Івано-Франківськ"
}

orders["місто"] = orders["місто"].replace(city_mapping)

print("Унікальні значення після узгодження:")
print(orders["місто"].unique())

Унікальні значення після узгодження:
<StringArray>
['Івано-Франківськ']
Length: 1, dtype: str

In [16]:
print("Тип ціни:", orders["ціна"].dtype)
print("Унікальні міста:", orders["місто"].unique())

orders

Тип ціни: float64
Унікальні міста: <StringArray>
['Івано-Франківськ']
Length: 1, dtype: str

   id        дата      товар             місто    ціна  кількість
0   1  2026-09-01  Product 7  Івано-Франківськ   760.0        3.0
1   2  2026-09-02  Product 7  Івано-Франківськ   760.0        4.0
2   3  2026-09-03  Product 7  Івано-Франківськ   760.0        3.5
3   4  2026-09-04  Product 7  Івано-Франківськ   760.0        2.0
4   5  2026-09-05  Product 7  Івано-Франківськ   760.0        3.5
5   6  2026-09-06  Product 7  Івано-Франківськ  7600.0        3.0
6   7  2026-09-07  Product 7  Івано-Франківськ   760.0        5.0

In [17]:
q1 = orders["ціна"].quantile(0.25)
q3 = orders["ціна"].quantile(0.75)

iqr = q3 - q1

lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr

print("Q1 =", q1)
print("Q3 =", q3)
print("IQR =", iqr)
print("Нижня межа =", lower)
print("Верхня межа =", upper)

Q1 = 760.0
Q3 = 760.0
IQR = 0.0
Нижня межа = 760.0
Верхня межа = 760.0

In [18]:
outliers = orders[
    (orders["ціна"] < lower) |
    (orders["ціна"] > upper)
]

print("Викиди:")
print(outliers)

Викиди:
   id        дата      товар             місто    ціна  кількість
5   6  2026-09-06  Product 7  Івано-Франківськ  7600.0        3.0

### Рішення щодо викиду

Значення 7600 грн було визначено як викид за правилом IQR. Для цього набору я вважаю це значення помилкою введення, оскільки базова ціна товару становить 760 грн, а значення 7600 грн рівно у 10 разів перевищує базову ціну. Найімовірніше, під час введення було випадково додано зайвий нуль. Тому це значення доцільно виправити до 760 грн, а не залишати як реальне велике замовлення.

In [19]:
orders.loc[orders["ціна"] == 7600, "ціна"] = 760

print("Ціни після виправлення:")
print(orders["ціна"].tolist())

Ціни після виправлення:
[760.0, 760.0, 760.0, 760.0, 760.0, 760.0, 760.0]

In [20]:
print("Пропуски:")
print(orders.isna().sum())

print("\nДублікати:")
print(orders.duplicated().sum())

print("\nТипи даних:")
print(orders.dtypes)

print("\nУнікальні міста:")
print(orders["місто"].unique())

print("\nКількість рядків:", len(orders))

print("\nОчищений набір:")
orders

Пропуски:
id           0
дата         0
товар        0
місто        0
ціна         0
кількість    0
dtype: int64

Дублікати:
0

Типи даних:
id             int64
дата             str
товар            str
місто            str
ціна         float64
кількість    float64
dtype: object

Унікальні міста:
<StringArray>
['Івано-Франківськ']
Length: 1, dtype: str

Кількість рядків: 7

Очищений набір:

   id        дата      товар             місто   ціна  кількість
0   1  2026-09-01  Product 7  Івано-Франківськ  760.0        3.0
1   2  2026-09-02  Product 7  Івано-Франківськ  760.0        4.0
2   3  2026-09-03  Product 7  Івано-Франківськ  760.0        3.5
3   4  2026-09-04  Product 7  Івано-Франківськ  760.0        2.0
4   5  2026-09-05  Product 7  Івано-Франківськ  760.0        3.5
5   6  2026-09-06  Product 7  Івано-Франківськ  760.0        3.0
6   7  2026-09-07  Product 7  Івано-Франківськ  760.0        5.0

## Письмові відповіді

### 1. Чому середнє може спотворити стандартне відхилення?

Заповнення пропусків середнім може зменшити розкид даних, тому стандартне відхилення може вийти штучно меншим. Медіана краще підходить для невеликого набору даних і менше залежить від крайніх значень.

### 2. У чому різниця між duplicated() без subset і з subset?

Без subset метод перевіряє повний збіг усього рядка. З subset перевіряються тільки вказані стовпці. Тому кількість знайдених дублікатів може відрізнятися.

### 3. Чому не можна автоматично видаляти всі значення поза IQR?

Значення поза межами IQR не завжди є помилками. Це може бути реальне незвичайне значення. Тому його потрібно перевірити перед видаленням.

## Висновок

Під час практичної роботи було очищено набір даних для варіанта 7 — Івано-Франківськ. Було знайдено та виправлено пропуски, дублікат, неправильний тип ціни, різні назви міста та викид.

У результаті отримано чистий набір даних без пропусків і дублікатів, із правильними типами даних та єдиною назвою міста.